/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'seniorAdmin' : IDL.Null,
  'owner' : IDL.Null,
  'staff' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Nat,
  'inactivityWarnings' : IDL.Nat,
  'username' : IDL.Text,
  'password' : IDL.Text,
  'role' : UserRole,
  'isOnline' : IDL.Bool,
  'demotionWarning' : IDL.Bool,
  'lastCheckIn' : IDL.Int,
});
export const Announcement = IDL.Record({
  'id' : IDL.Nat,
  'authorUsername' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'checkIn' : IDL.Func([IDL.Nat], [], []),
  'checkOut' : IDL.Func([IDL.Nat], [], []),
  'demoteUser' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'getAllPasswords' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Variant({
          'ok' : IDL.Vec(
            IDL.Record({
              'username' : IDL.Text,
              'password' : IDL.Text,
              'role' : IDL.Text,
            })
          ),
          'err' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getAllUsers' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Vec(UserProfile), 'err' : IDL.Text })],
      ['query'],
    ),
  'getAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getAttendanceBoard' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'username' : IDL.Text,
            'userId' : IDL.Nat,
            'role' : IDL.Text,
            'isOnline' : IDL.Bool,
            'lastCheckIn' : IDL.Int,
            'inactivityDays' : IDL.Nat,
          })
        ),
      ],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getCurrentUser' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getDemotionCandidates' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getNotifications' : IDL.Func([IDL.Nat], [IDL.Vec(Notification)], ['query']),
  'getUserById' : IDL.Func([IDL.Nat], [IDL.Opt(UserProfile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'login' : IDL.Func(
      [IDL.Text, IDL.Text],
      [
        IDL.Variant({
          'ok' : IDL.Record({ 'userId' : IDL.Nat, 'role' : IDL.Text }),
          'err' : IDL.Text,
        }),
      ],
      [],
    ),
  'markNotificationRead' : IDL.Func([IDL.Nat], [], []),
  'runInactivityCheck' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendAnnouncement' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'seniorAdmin' : IDL.Null,
    'owner' : IDL.Null,
    'staff' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Nat,
    'inactivityWarnings' : IDL.Nat,
    'username' : IDL.Text,
    'password' : IDL.Text,
    'role' : UserRole,
    'isOnline' : IDL.Bool,
    'demotionWarning' : IDL.Bool,
    'lastCheckIn' : IDL.Int,
  });
  const Announcement = IDL.Record({
    'id' : IDL.Nat,
    'authorUsername' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'checkIn' : IDL.Func([IDL.Nat], [], []),
    'checkOut' : IDL.Func([IDL.Nat], [], []),
    'demoteUser' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'getAllPasswords' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Variant({
            'ok' : IDL.Vec(
              IDL.Record({
                'username' : IDL.Text,
                'password' : IDL.Text,
                'role' : IDL.Text,
              })
            ),
            'err' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getAllUsers' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Vec(UserProfile), 'err' : IDL.Text })],
        ['query'],
      ),
    'getAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getAttendanceBoard' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'username' : IDL.Text,
              'userId' : IDL.Nat,
              'role' : IDL.Text,
              'isOnline' : IDL.Bool,
              'lastCheckIn' : IDL.Int,
              'inactivityDays' : IDL.Nat,
            })
          ),
        ],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getCurrentUser' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getDemotionCandidates' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getNotifications' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'getUserById' : IDL.Func([IDL.Nat], [IDL.Opt(UserProfile)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'login' : IDL.Func(
        [IDL.Text, IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Record({ 'userId' : IDL.Nat, 'role' : IDL.Text }),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'markNotificationRead' : IDL.Func([IDL.Nat], [], []),
    'runInactivityCheck' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendAnnouncement' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };