/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'id' : bigint,
  'authorUsername' : string,
  'message' : string,
  'timestamp' : bigint,
}
export interface Notification {
  'id' : bigint,
  'isRead' : boolean,
  'message' : string,
  'timestamp' : bigint,
}
export interface UserProfile {
  'id' : bigint,
  'inactivityWarnings' : bigint,
  'username' : string,
  'password' : string,
  'role' : UserRole,
  'isOnline' : boolean,
  'demotionWarning' : boolean,
  'lastCheckIn' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'seniorAdmin' : null } |
  { 'owner' : null } |
  { 'staff' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'checkIn' : ActorMethod<[bigint], undefined>,
  'checkOut' : ActorMethod<[bigint], undefined>,
  'demoteUser' : ActorMethod<
    [bigint, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'getAllPasswords' : ActorMethod<
    [bigint],
    {
        'ok' : Array<
          { 'username' : string, 'password' : string, 'role' : string }
        >
      } |
      { 'err' : string }
  >,
  'getAllUsers' : ActorMethod<
    [bigint],
    { 'ok' : Array<UserProfile> } |
      { 'err' : string }
  >,
  'getAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getAttendanceBoard' : ActorMethod<
    [],
    Array<
      {
        'username' : string,
        'userId' : bigint,
        'role' : string,
        'isOnline' : boolean,
        'lastCheckIn' : bigint,
        'inactivityDays' : bigint,
      }
    >
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getCurrentUser' : ActorMethod<[], [] | [UserProfile]>,
  'getDemotionCandidates' : ActorMethod<[], Array<UserProfile>>,
  'getNotifications' : ActorMethod<[bigint], Array<Notification>>,
  'getUserById' : ActorMethod<[bigint], [] | [UserProfile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'login' : ActorMethod<
    [string, string],
    { 'ok' : { 'userId' : bigint, 'role' : string } } |
      { 'err' : string }
  >,
  'markNotificationRead' : ActorMethod<[bigint], undefined>,
  'runInactivityCheck' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendAnnouncement' : ActorMethod<
    [bigint, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];